apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
  - port: 3333
    targetPort: 3333
    protocol: TCP
    name: http
  type: ClusterIP
