apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
      - name: api
        resources:
          limits:
            cpu: 300m
            memory: 384Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: NODE_ENV
          value: development
